### ISSUE TITLE
Feature Request: Limit field group to a specific page?

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql-acf#1]
On many sites we build, we often have many ACF field groups specific to the page you are editing. For example, if it's the "Front page", or a "Contact page", or a top level page of some sort, or if this is a child page. It would be a real bummer if our "Contact" ACF field group has to be on every page.

I saw in Slack you plan on allowing us to limit field groups to custom templates, but that's not ideal. It will mean having to create a bunch of empty PHP files just for this, and page templates don't work great with custom post types either.

It seems the limitation is WP GQL not knowing the ID or page name during the query. Is there a better way we could come up with then? Perhaps our own rule set of some other data? A meta field called "Developer ID" perhaps? Or even the URI perhaps?

![Screen Shot 2019-04-25 at 3 56 48 PM](https://user-images.githubusercontent.com/475015/56773412-d6409480-6772-11e9-8951-a438583aa857.png)

**Comment by jasonbahl** [comment]
@drewbaker I'm super close to to having support for this. Plan to have it in release v0.1.4

**Comment by creazy231** [comment]
@jasonbahl is there any update on this issue? I got an update today for v0.1.4 but there are no changelogs in the releases tab on github.

**Comment by jasonbahl** [comment]
@creazy231 this one is still in progress. Getting close. Hope to have it within 2 weeks. Looking like it will be sooner than that, but don't want to overpromise.

**Comment by creazy231** [comment]
@jasonbahl thanks for the fast reply 👍
Just purchased a single license to try if I can get the results I need and defining rules is one one the main things I need. If this works as I look forward to purchase a lifetime license.

**Comment by jasonbahl** [comment]
Sweet! I just sent you an email reply as well 😀

**Comment by creazy231** [comment]
Awesome just like the job you're doing 💯

**Comment by creazy231** [comment]
Is there any progress made? 😁
Really need this feature for a upcoming project and I'd love to use tool (:

**Comment by jasonbahl** [comment]
@creazy231 yes. Had to fix a few bugs first but this will be in the next release 😀

**Comment by creazy231** [comment]
Awesome news 👍🏻
Any ETA? Can't wait to see it in production 😁

**Comment by creazy231** [comment]
Any update? 😋

**Comment by jasonbahl** [comment]
@creazy231 hey! I’m actually transitioning out of my current full time job to start working on WPGraphQL full-time. So the past few weeks have been consumed with that transition out of my current role. Monday I start full time on WPGraphQL so features like this that have been delayed will get addressed next week or shortly after. 

Thanks for your patience. Looking forward to getting these awaited features knocked out.

**Comment by creazy231** [comment]
Awesome news and good luck 🤞
I also recommended your plugin in the nuxt community discord #headless

**Comment by jasonbahl** [comment]
Got this working locally. Running through some things, but hoping to have a release together shortly.

**Comment by jasonbahl** [comment]
This was fixed, but a bug crept in. Closed by #24. Thanks @jayarnielsen!

**Comment by firestar300** [comment]
Hello @jasonbahl 

I still have the problem. I have specifics ACF fields for Front Page. 

<img width="950" alt="Capture d’écran 2019-08-28 à 20 50 46" src="https://user-images.githubusercontent.com/2543936/63883939-8cdcac00-c9d5-11e9-839e-cd0fa72cc7b7.png">

```"Page type | equal to | Front Page"```

But it doesn't appear in the schema.

<img width="1243" alt="Capture d’écran 2019-08-28 à 20 53 44" src="https://user-images.githubusercontent.com/2543936/63884151-f361ca00-c9d5-11e9-8012-a699bbb70789.png">

The ACF Fields Show in GraphQL is set to "1".

<img width="940" alt="Capture d’écran 2019-08-28 à 20 54 09" src="https://user-images.githubusercontent.com/2543936/63884268-24da9580-c9d6-11e9-8810-f17d324d074f.png">

Did I miss something ?

**Comment by treb0r** [comment]
@jasonbahl Same issue here. Can't access a field group via Graphql from a specific page. It works if I set the location to all pages (by post type).

WP GraphQL Version 0.3.3
WPGraphQL for Advanced Custom Fields Version 0.2.0

**Comment by rrLucho** [comment]
I've been dealing with this for a few hours too.
I installed the WP GraphiQL plugin and the field group shows fine there, but on my local application, it won't show up in the schema.

Has there been any updates on this?

**Comment by davemcnally** [comment]
I'm struggling with a similar, if not the same issue here — A field group will show up in the schema when location is all pages via post type. However if I add an `and` condition to rule out a specific page, it's removed entirely, even if just querying a page still allowed to show the field group by that rule.

**Comment by sirichards** [comment]
I have a similar issue, when a field group is attached to a page based on its page template. 
The fields are not showing up. Is there a work around for this?

![1](https://user-images.githubusercontent.com/21104091/74440372-cca12e00-4e65-11ea-9701-5a0a7f9e1b43.jpg)

![2](https://user-images.githubusercontent.com/21104091/74440308-af6c5f80-4e65-11ea-9604-517e2dc4b253.jpg)

![3](https://user-images.githubusercontent.com/21104091/74440418-e6427580-4e65-11ea-975c-597a1ec89d14.jpg)

**Comment by treb0r** [comment]
This issue is marked as closed but it's not actually fixed.

**Comment by brianshimkus** [comment]
@jasonbahl Was a solution ever found for the issue above?

**Comment by iryanclarke** [comment]
Another follow up on this, this is definitely something that our team needs, @brianshimkus Did you find a workaround?

Or is there an update from @jasonbahl

**Comment by drewbaker** [comment]
@jasonbahl This is still an issue. Should we reopen this or create a new ticket?

**Comment by drewbaker** [comment]
I'd be happy with the schema returning null (or error) for everything and just allowing the ACF location filters to just hide the UI in wordpress. This is a UI issue more than it is a GQL issue I think.

**Comment by drewbaker** [comment]
@kidunot89 Can I pay you to fix this? You think you can figure it out?

**Comment by kidunot89** [comment]
@drewbaker Sure, I'll look at it. Reach out to me in the WPGraphQL Slack :+1:

**Comment by tim9009** [comment]
I'm running in to this problem too. Did anyone find a fix for it?

**Comment by drewbaker** [comment]
@tim9009 try this PR out and comment there if you have any issues: https://github.com/wp-graphql/wp-graphql-acf/pull/207
