### ISSUE TITLE
Post meta values of 0 resolve to null for Number fields

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql-acf#164]
When I query an ACF Number field that has a post meta value of `0` in the database, the GraphQL API returns `null` for it.

## Steps to reproduce:

1. Register a Number ACF field on a post type
1. Save one post with `5` (or any other number) as that field's value
1. Save another post with `0` as that field's value
1. Query for those two posts & field values via GraphQL and confirm that the values in the response are `5` and `null`, respectively.

## Expected behavior
If the value of a Number field in the database is `0`, then the value returning by the GraphQL API should also be `0`.

## Versions used for testing
WPGraphQL for Advanced Custom Fields 0.3.5
WPGraphQL 0.12.0
ACF Pro 5.5.11
WordPress 5.5

**Comment by arbaouimehdi** [comment]
# Steps to reproduce
- I created a mutation called `startQuiz` that will set the Quiz Score at its initial value `0`, the value is stored correctly.

![](https://i.ibb.co/mJTRZT5/Screen-Shot-2021-02-18-at-14-54-22.png)

- On the other side, and when running the GraphQL query, it returns `null` instead of `0`.

![](https://i.ibb.co/WvQdFMV/Screen-Shot-2021-02-18-at-14-55-58.png)

# Versions used for testing
- WPGraphQL for Advanced Custom Fields 0.4.1
- WPGraphQL 1.1.3
- ACF Pro 5.9.3
- WordPress 5.6.1

**Comment by jasonbahl** [comment]
This is resolved in the upcoming v0.6.0 (#262)

See: https://github.com/wp-graphql/wp-graphql-acf/issues/237#issuecomment-840760327

**Comment by ShahriarKh** [comment]
How long does it take to release v0.6.0 with this fix?

**Comment by sharmarch** [comment]
Hi @jasonbahl I'm still seeing this issue for both text and number fields, for parent fields and fields within a Group or Repeater.

**Versions:**
- WPGraphQL for Advanced Custom Fields 0.6.1
- WordPress 6.0.2
- WP GraphQL 1.12.0
- ACF Pro 6.0.3 

![Screen Shot 2022-10-25 at 2 14 09 PM](https://user-images.githubusercontent.com/918329/197873428-4db47fd3-ac7a-4bb7-a52f-fcc64527667e.jpg)
![Screen Shot 2022-10-25 at 2 02 29 PM](https://user-images.githubusercontent.com/918329/197873467-1ea38d70-b3a1-4100-bee0-1a1964011435.jpg)

**Comment by Paximilianus** [comment]
Hi @jasonbahl 

I'm also getting null instead of 0 (number)

Pretty much same setup as above

WPGraphQL for Advanced Custom Fields 0.6.1
WordPress 6.0.2
WP GraphQL 1.12.0
ACF 6.0.3

also using

Custom Post Type UI 1.13.1

**Comment by marco910** [comment]
Hi there, I'm also facing this issue. Any updates on this?

**Comment by marco910** [comment]
Any updates on this? Still experiencing this issue in the latest version

**Comment by KrimoPixelsmith** [comment]
Same here, still experiencing the issue

**Comment by sean-e-dietrich** [comment]
Still experiencing this issue, any updates?

**Comment by jasonbahl** [comment]
@sean-e-dietrich what version of WPGraphQL for ACF are you on? this is the repository for the old v0.6.* and older. The new version v2.* and newer is over at https://github.com/wp-graphql/wpgraphql-acf and this repo will be archived soon.

**Comment by jasonbahl** [comment]
@sean-e-dietrich looks like an issue exists on the new repo: https://github.com/wp-graphql/wpgraphql-acf/issues/215
